using System;
using System.Collections.Generic;
using UnityEngine;

namespace BillUtils.GlobalTimeUtils
{
    public static class GlobalTimeUtils
    {
        public static DateTime GetCurrentTimeAtTimeZone(string timeZoneId)
        {
            try
            {
                DateTime utcNow = DateTime.UtcNow;

                string windowsTimeZoneId = IanaToWindowsTimeZone(timeZoneId);
                if (windowsTimeZoneId == null)
                {
                    return DateTime.MinValue;
                }

                TimeZoneInfo timeZone = TimeZoneInfo.FindSystemTimeZoneById(windowsTimeZoneId);
                DateTime localTime = TimeZoneInfo.ConvertTimeFromUtc(utcNow, timeZone);

                return localTime;
            }
            catch (TimeZoneNotFoundException)
            {
                return DateTime.MinValue;
            }
            catch (InvalidTimeZoneException)
            {
                return DateTime.MinValue;
            }
            catch (Exception ex)
            {
                return DateTime.MinValue;
            }
        }
        private static string IanaToWindowsTimeZone(string ianaTimeZoneId)
        {
            if (IanaToWindowsTimeZoneMap.TryGetValue(ianaTimeZoneId, out string windowsTimeZoneId))
            {
                return windowsTimeZoneId;
            }
            else
            {
                Debug.LogError($"Time zone '{ianaTimeZoneId}' not found in the map.");
                return null;
            }
        }

        #region CONFIG TIME ZONE
        private static readonly Dictionary<string, string> IanaToWindowsTimeZoneMap = new Dictionary<string, string>
        {
            { "Africa/Abidjan", "Greenwich Standard Time" },
            { "Africa/Accra", "Greenwich Standard Time" },
            { "Africa/Addis_Ababa", "E. Africa Standard Time" },
            { "Africa/Algiers", "W. Central Africa Standard Time" },
            { "Africa/Asmara", "E. Africa Standard Time" },
            { "Africa/Bamako", "Greenwich Standard Time" },
            { "Africa/Bangui", "W. Central Africa Standard Time" },
            { "Africa/Banjul", "Greenwich Standard Time" },
            { "Africa/Bissau", "Greenwich Standard Time" },
            { "Africa/Blantyre", "South Africa Standard Time" },
            { "Africa/Brazzaville", "W. Central Africa Standard Time" },
            { "Africa/Bujumbura", "South Africa Standard Time" },
            { "Africa/Cairo", "Egypt Standard Time" },
            { "Africa/Casablanca", "Morocco Standard Time" },
            { "Africa/Ceuta", "Romance Standard Time" },
            { "Africa/Conakry", "Greenwich Standard Time" },
            { "Africa/Dakar", "Greenwich Standard Time" },
            { "Africa/Dar_es_Salaam", "E. Africa Standard Time" },
            { "Africa/Djibouti", "E. Africa Standard Time" },
            { "Africa/Douala", "W. Central Africa Standard Time" },
            { "Africa/El_Aaiun", "Morocco Standard Time" },
            { "Africa/Freetown", "Greenwich Standard Time" },
            { "Africa/Gaborone", "South Africa Standard Time" },
            { "Africa/Harare", "South Africa Standard Time" },
            { "Africa/Johannesburg", "South Africa Standard Time" },
            { "Africa/Juba", "E. Africa Standard Time" },
            { "Africa/Kampala", "E. Africa Standard Time" },
            { "Africa/Khartoum", "E. Africa Standard Time" },
            { "Africa/Kigali", "South Africa Standard Time" },
            { "Africa/Kinshasa", "W. Central Africa Standard Time" },
            { "Africa/Lagos", "W. Central Africa Standard Time" },
            { "Africa/Libreville", "W. Central Africa Standard Time" },
            { "Africa/Lome", "Greenwich Standard Time" },
            { "Africa/Luanda", "W. Central Africa Standard Time" },
            { "Africa/Lubumbashi", "South Africa Standard Time" },
            { "Africa/Lusaka", "South Africa Standard Time" },
            { "Africa/Malabo", "W. Central Africa Standard Time" },
            { "Africa/Maputo", "South Africa Standard Time" },
            { "Africa/Maseru", "South Africa Standard Time" },
            { "Africa/Mbabane", "South Africa Standard Time" },
            { "Africa/Mogadishu", "E. Africa Standard Time" },
            { "Africa/Monrovia", "Greenwich Standard Time" },
            { "Africa/Nairobi", "E. Africa Standard Time" },
            { "Africa/Ndjamena", "W. Central Africa Standard Time" },
            { "Africa/Niamey", "W. Central Africa Standard Time" },
            { "Africa/Nouakchott", "Greenwich Standard Time" },
            { "Africa/Ouagadougou", "Greenwich Standard Time" },
            { "Africa/Porto-Novo", "W. Central Africa Standard Time" },
            { "Africa/Sao_Tome", "Greenwich Standard Time" },
            { "Africa/Tripoli", "Libya Standard Time" },
            { "Africa/Tunis", "W. Central Africa Standard Time" },
            { "Africa/Windhoek", "Namibia Standard Time" },
            { "America/Adak", "Hawaiian Standard Time" },
            { "America/Anchorage", "Alaskan Standard Time" },
            { "America/Anguilla", "SA Western Standard Time" },
            { "America/Antigua", "SA Western Standard Time" },
            { "America/Araguaina", "E. South America Standard Time" },
            { "America/Argentina/Buenos_Aires", "Argentina Standard Time" },
            { "America/Argentina/Catamarca", "Argentina Standard Time" },
            { "America/Argentina/Cordoba", "Argentina Standard Time" },
            { "America/Argentina/Jujuy", "Argentina Standard Time" },
            { "America/Argentina/La_Rioja", "Argentina Standard Time" },
            { "America/Argentina/Mendoza", "Argentina Standard Time" },
            { "America/Argentina/Rio_Gallegos", "Argentina Standard Time" },
            { "America/Argentina/Salta", "Argentina Standard Time" },
            { "America/Argentina/San_Juan", "Argentina Standard Time" },
            { "America/Argentina/San_Luis", "Argentina Standard Time" },
            { "America/Argentina/Tucuman", "Argentina Standard Time" },
            { "America/Argentina/Ushuaia", "Argentina Standard Time" },
            { "America/Aruba", "SA Western Standard Time" },
            { "America/Asuncion", "Paraguay Standard Time" },
            { "America/Atikokan", "Eastern Standard Time" },
            { "America/Bahia", "Bahia Standard Time" },
            { "America/Bahia_Banderas", "Central Standard Time (Mexico)" },
            { "America/Barbados", "SA Western Standard Time" },
            { "America/Belem", "SA Eastern Standard Time" },
            { "America/Belize", "Central America Standard Time" },
            { "America/Blanc-Sablon", "SA Western Standard Time" },
            { "America/Boa_Vista", "SA Western Standard Time" },
            { "America/Bogota", "SA Pacific Standard Time" },
            { "America/Boise", "Mountain Standard Time" },
            { "America/Cambridge_Bay", "Mountain Standard Time" },
            { "America/Campo_Grande", "Central Brazilian Standard Time" },
            { "America/Cancun", "Eastern Standard Time (Mexico)" },
            { "America/Caracas", "Venezuela Standard Time" },
            { "America/Cayenne", "SA Eastern Standard Time" },
            { "America/Cayman", "SA Western Standard Time" },
            { "America/Chicago", "Central Standard Time" },
            { "America/Chihuahua", "Mountain Standard Time (Mexico)" },
            { "America/Costa_Rica", "Central America Standard Time" },
            { "America/Creston", "US Mountain Standard Time" },
            { "America/Cuiaba", "Central Brazilian Standard Time" },
            { "America/Curacao", "SA Western Standard Time" },
            { "America/Danmarkshavn", "Greenwich Standard Time" },
            { "America/Dawson", "Pacific Standard Time" },
            { "America/Dawson_Creek", "US Mountain Standard Time" },
            { "America/Denver", "Mountain Standard Time" },
            { "America/Detroit", "Eastern Standard Time" },
            { "America/Dominica", "SA Western Standard Time" },
            { "America/Edmonton", "Mountain Standard Time" },
            { "America/Eirunepe", "SA Western Standard Time" },
            { "America/El_Salvador", "Central America Standard Time" },
            { "America/Fort_Nelson", "US Mountain Standard Time" },
            { "America/Fortaleza", "SA Eastern Standard Time" },
            { "America/Glace_Bay", "Atlantic Standard Time" },
            { "America/Godthab", "Greenland Standard Time" },
            { "America/Goose_Bay", "Atlantic Standard Time" },
            { "America/Grand_Turk", "Eastern Standard Time" },
            { "America/Grenada", "SA Western Standard Time" },
            { "America/Guadeloupe", "SA Western Standard Time" },
            { "America/Guatemala", "Central America Standard Time" },
            { "America/Guayaquil", "SA Pacific Standard Time" },
            { "America/Guyana", "SA Western Standard Time" },
            { "America/Halifax", "Atlantic Standard Time" },
            { "America/Havana", "Cuba Standard Time" },
            { "America/Hermosillo", "US Mountain Standard Time" },
            { "America/Indiana/Indianapolis", "Eastern Standard Time" },
            { "America/Indiana/Knox", "Central Standard Time" },
            { "America/Indiana/Marengo", "Eastern Standard Time" },
            { "America/Indiana/Petersburg", "Eastern Standard Time" },
            { "America/Indiana/Tell_City", "Central Standard Time" },
            { "America/Indiana/Vevay", "Eastern Standard Time" },
            { "America/Indiana/Vincennes", "Eastern Standard Time" },
            { "America/Indiana/Winamac", "Eastern Standard Time" },
            { "America/Inuvik", "Mountain Standard Time" },
            { "America/Iqaluit", "Eastern Standard Time" },
            { "America/Jamaica", "SA Western Standard Time" },
            { "America/Juneau", "Alaskan Standard Time" },
            { "America/Kentucky/Louisville", "Eastern Standard Time" },
            { "America/Kentucky/Monticello", "Eastern Standard Time" },
            { "America/Kralendijk", "SA Western Standard Time" },
            { "America/La_Paz", "SA Western Standard Time" },
            { "America/Lima", "SA Pacific Standard Time" },
            { "America/Los_Angeles", "Pacific Standard Time" },
            { "America/Lower_Princes", "SA Western Standard Time" },
            { "America/Maceio", "SA Eastern Standard Time" },
            { "America/Managua", "Central America Standard Time" },
            { "America/Manaus", "SA Western Standard Time" },
            { "America/Marigot", "SA Western Standard Time" },
            { "America/Martinique", "SA Western Standard Time" },
            { "America/Matamoros", "Central Standard Time" },
            { "America/Mazatlan", "Mountain Standard Time (Mexico)" },
            { "America/Menominee", "Central Standard Time" },
            { "America/Merida", "Central Standard Time (Mexico)" },
            { "America/Metlakatla", "Alaskan Standard Time" },
            { "America/Mexico_City", "Central Standard Time (Mexico)" },
            { "America/Miquelon", "SA Western Standard Time" },
            { "America/Moncton", "Atlantic Standard Time" },
            { "America/Monterrey", "Central Standard Time (Mexico)" },
            { "America/Montevideo", "Montevideo Standard Time" },
            { "America/Montserrat", "SA Western Standard Time" },
            { "America/Nassau", "Eastern Standard Time" },
            { "America/New_York", "Eastern Standard Time" },
            { "America/Nipigon", "Eastern Standard Time" },
            { "America/Nome", "Alaskan Standard Time" },
            { "America/Noronha", "UTC-02" },
            { "America/North_Dakota/Beulah", "Central Standard Time" },
            { "America/North_Dakota/Center", "Central Standard Time" },
            { "America/North_Dakota/New_Salem", "Central Standard Time" },
            { "America/Ojinaga", "Mountain Standard Time" },
            { "America/Panama", "SA Pacific Standard Time" },
            { "America/Pangnirtung", "Eastern Standard Time" },
            { "America/Paramaribo", "SA Western Standard Time" },
            { "America/Phoenix", "US Mountain Standard Time" },
            { "America/Port-au-Prince", "SA Western Standard Time" },
            { "America/Port_of_Spain", "SA Western Standard Time" },
            { "America/Porto_Velho", "SA Western Standard Time" },
            { "America/Puerto_Rico", "SA Western Standard Time" },
            { "America/Punta_Arenas", "Magallanes Standard Time" },
            { "America/Rainy_River", "Central Standard Time" },
            { "America/Rankin_Inlet", "Central Standard Time" },
            { "America/Recife", "SA Eastern Standard Time" },
            { "America/Regina", "Canada Central Standard Time" },
            { "America/Resolute", "Central Standard Time" },
            { "America/Rio_Branco", "SA Western Standard Time" },
            { "America/Santarem", "SA Eastern Standard Time" },
            { "America/Santiago", "Pacific SA Standard Time" },
            { "America/Santo_Domingo", "SA Western Standard Time" },
            { "America/Sao_Paulo", "E. South America Standard Time" },
            { "America/Scoresbysund", "Azores Standard Time" },
            { "America/Sitka", "Alaskan Standard Time" },
            { "America/St_Barthelemy", "SA Western Standard Time" },
            { "America/St_Johns", "Newfoundland Standard Time" },
            { "America/St_Kitts", "SA Western Standard Time" },
            { "America/St_Lucia", "SA Western Standard Time" },
            { "America/St_Thomas", "SA Western Standard Time" },
            { "America/St_Vincent", "SA WesternStandard Time" },
            { "America/Swift_Current", "Canada Central Standard Time" },
            { "America/Tegucigalpa", "Central America Standard Time" },
            { "America/Thule", "Atlantic Standard Time" },
            { "America/Thunder_Bay", "Eastern Standard Time" },
            { "America/Tijuana", "Pacific Standard Time (Mexico)" },
            { "America/Toronto", "Eastern Standard Time" },
            { "America/Tortola", "SA Western Standard Time" },
            { "America/Vancouver", "Pacific Standard Time" },
            { "America/Whitehorse", "Pacific Standard Time" },
            { "America/Winnipeg", "Central Standard Time" },
            { "America/Yakutat", "Alaskan Standard Time" },
            { "America/Yellowknife", "Mountain Standard Time" },
            { "Antarctica/Casey", "W. Australia Standard Time" },
            { "Antarctica/Davis", "SE Asia Standard Time" },
            { "Antarctica/DumontDUrville", "West Pacific Standard Time" },
            { "Antarctica/Macquarie", "AUS Eastern Standard Time" },
            { "Antarctica/Mawson", "Central Asia Standard Time" },
            { "Antarctica/McMurdo", "New Zealand Standard Time" },
            { "Antarctica/Palmer", "SA Western Standard Time" },
            { "Antarctica/Rothera", "SA Eastern Standard Time" },
            { "Antarctica/Syowa", "E. Africa Standard Time" },
            { "Antarctica/Troll", "Greenwich Standard Time" },
            { "Antarctica/Vostok", "Central Asia Standard Time" },
            { "Arctic/Longyearbyen", "W. Europe Standard Time" },
            { "Asia/Aden", "Arabic Standard Time" },
            { "Asia/Almaty", "Central Asia Standard Time" },
            { "Asia/Amman", "Jordan Standard Time" },
            { "Asia/Anadyr", "Russia Time Zone 11" },
            { "Asia/Aqtau", "West Asia Standard Time" },
            { "Asia/Aqtobe", "West Asia Standard Time" },
            { "Asia/Ashgabat", "West Asia Standard Time" },
            { "Asia/Atyrau", "West Asia Standard Time" },
            { "Asia/Baghdad", "Arabic Standard Time" },
            { "Asia/Bahrain", "Arabic Standard Time" },
            { "Asia/Baku", "Azerbaijan Standard Time" },
            { "Asia/Bangkok", "SE Asia Standard Time" },
            { "Asia/Barnaul", "Altai Standard Time" },
            { "Asia/Beirut", "Middle East Standard Time" },
            { "Asia/Bishkek", "Central Asia Standard Time" },
            { "Asia/Brunei", "Singapore Standard Time" },
            { "Asia/Chita", "Transbaikal Standard Time" },
            { "Asia/Choibalsan", "Ulaanbaatar Standard Time" },
            { "Asia/Colombo", "India Standard Time" },
            { "Asia/Damascus", "Syria Standard Time" },
            { "Asia/Dhaka", "Bangladesh Standard Time" },
            { "Asia/Dili", "Tokyo Standard Time" },
            { "Asia/Dubai", "Arabian Standard Time" },
            { "Asia/Dushanbe", "West Asia Standard Time" },
            { "Asia/Famagusta", "GTB Standard Time" },
            { "Asia/Gaza", "Israel Standard Time" },
            { "Asia/Hebron", "Israel Standard Time" },
            { "Asia/Ho_Chi_Minh", "SE Asia Standard Time" },
            { "Asia/Hong_Kong", "China Standard Time" },
            { "Asia/Hovd", "W. Mongolia Standard Time" },
            { "Asia/Irkutsk", "North Asia East Standard Time" },
            { "Asia/Jakarta", "SE Asia Standard Time" },
            { "Asia/Jayapura", "Tokyo Standard Time" },
            { "Asia/Jerusalem", "Israel Standard Time" },
            { "Asia/Kabul", "Afghanistan Standard Time" },
            { "Asia/Kamchatka", "Russia Time Zone 11" },
            { "Asia/Karachi", "Pakistan Standard Time" },
            { "Asia/Kathmandu", "Nepal Standard Time" },
            { "Asia/Khandyga", "Yakutsk Standard Time" },
            { "Asia/Kolkata", "India Standard Time" },
            { "Asia/Krasnoyarsk", "North Asia Standard Time" },
            { "Asia/Kuala_Lumpur", "Singapore Standard Time" },
            { "Asia/Kuching", "Singapore Standard Time" },
            { "Asia/Kuwait", "Arab Standard Time" },
            { "Asia/Macau", "China Standard Time" },
            { "Asia/Magadan", "Magadan Standard Time" },
            { "Asia/Makassar", "Central Indonesia Standard Time" },
            { "Asia/Manila", "Singapore Standard Time" },
            { "Asia/Muscat", "Arabian Standard Time" },
            { "Asia/Nicosia", "GTB Standard Time" },
            { "Asia/Novokuznetsk", "North Asia Standard Time" },
            { "Asia/Novosibirsk", "N. Central Asia Standard Time" },
            { "Asia/Omsk", "Omsk Standard Time" },
            { "Asia/Oral", "West Asia Standard Time" },
            { "Asia/Phnom_Penh", "SE Asia Standard Time" },
            { "Asia/Pontianak", "SE Asia Standard Time" },
            { "Asia/Pyongyang", "North Korea Standard Time" },
            { "Asia/Qatar", "Arab Standard Time" },
            { "Asia/Qostanay", "Central Asia Standard Time" },
            { "Asia/Qyzylorda", "Central Asia Standard Time" },
            { "Asia/Riyadh", "Arab Standard Time" },
            { "Asia/Sakhalin", "Sakhalin Standard Time" },
            { "Asia/Samarkand", "West Asia Standard Time" },
            { "Asia/Seoul", "Korea Standard Time" },
            { "Asia/Shanghai", "China Standard Time" },
            { "Asia/Singapore", "Singapore Standard Time" },
            { "Asia/Srednekolymsk", "Russia Time Zone 11" },
            { "Asia/Taipei", "Taipei Standard Time" },
            { "Asia/Tashkent", "West Asia Standard Time" },
            { "Asia/Tbilisi", "Georgian Standard Time" },
            { "Asia/Tehran", "Iran Standard Time" },
            { "Asia/Thimphu", "Bangladesh Standard Time" },
            { "Asia/Tokyo", "Tokyo Standard Time"},
            { "Asia/Tomsk", "Russia Time Zone 7" },
            { "Asia/Ulaanbaatar", "Ulaanbaatar Standard Time" },
            { "Asia/Urumqi", "Central Asia Standard Time" },
            { "Asia/Ust-Nera", "Vladivostok Standard Time" },
            { "Asia/Vientiane", "SE Asia Standard Time" },
            { "Asia/Vladivostok", "Vladivostok Standard Time" },
            { "Asia/Yakutsk", "Yakutsk Standard Time" },
            { "Asia/Yangon", "Myanmar Standard Time" },
            { "Asia/Yekaterinburg", "Ekaterinburg Standard Time" },
            { "Asia/Yerevan", "Caucasus Standard Time" },
            { "Atlantic/Azores", "Azores Standard Time" },
            { "Atlantic/Bermuda", "SA Western Standard Time" },
            { "Atlantic/Canary", "GMT Standard Time" },
            { "Atlantic/Cape_Verde", "Cape Verde Standard Time" },
            { "Atlantic/Faroe", "GMT Standard Time" },
            { "Atlantic/Madeira", "GMT Standard Time" },
            { "Atlantic/Reykjavik", "Greenwich Standard Time" },
            { "Atlantic/South_Georgia", "UTC-02" },
            { "Atlantic/St_Helena", "Greenwich Standard Time" },
            { "Atlantic/Stanley", "SA Western Standard Time" },
            { "Australia/Adelaide", "Cen. Australia Standard Time" },
            { "Australia/Brisbane", "E. Australia Standard Time" },
            { "Australia/Broken_Hill", "Cen. Australia Standard Time" },
            { "Australia/Currie", "Tasmania Standard Time" },
            { "Australia/Darwin", "AUS Central Standard Time" },
            { "Australia/Eucla", "Aus Central W. Standard Time" },
            { "Australia/Hobart", "Tasmania Standard Time" },
            { "Australia/Lindeman", "E. Australia Standard Time" },
            { "Australia/Lord_Howe", "Lord Howe Standard Time" },
            { "Australia/Melbourne", "AUS Eastern Standard Time" },
            { "Australia/Perth", "W. Australia Standard Time" },
            { "Australia/Sydney", "AUS Eastern Standard Time" },
            { "CET", "W. Europe Standard Time" },
            { "CST6CDT", "Central Standard Time" },
            { "EET", "E. Europe Standard Time" },
            { "EST", "Eastern Standard Time" },
            { "EST5EDT", "Eastern Standard Time" },
            { "HST", "Hawaiian Standard Time" },
            { "MET", "W. Europe Standard Time" },
            { "MST", "Mountain Standard Time" },
            { "MST7MDT", "Mountain Standard Time" },
            { "PST8PDT", "Pacific Standard Time" },
            { "WET", "GMT Standard Time" }
        };
        #endregion
    }
}