from graphviz import Digraph

# Tạo đồ thị
dot = Digraph(comment='Block Management Flow')

# Thêm các node
dot.node('A', 'Start')
dot.node('B', 'Kiểm tra Pool')
dot.node('C', 'Có block trong pool')
dot.node('D', 'Không có block trong pool')
dot.node('E', 'Spawn block từ pool')
dot.node('F', 'Instantiate block mới')
dot.node('G', 'Block được spawn')
dot.node('H', 'Block mới được tạo')
dot.node('I', 'Quản lý Cube trong Reconstruct Mode')
dot.node('J', 'Khi có block')
dot.node('K', 'Cube bị phá hủy?')
dot.node('L', 'Có')
dot.node('M', 'Không')
dot.node('N', 'Đưa lại vào pool')
dot.node('O', 'Chuyển sang chế độ Reconstruct')
dot.node('P', 'Change Material')
dot.node('Q', 'Xuất hiện và có các tính năng khác')
dot.node('R', 'Move')
dot.node('S', 'Va chạm?')
dot.node('T', 'Đỏ nếu có')
dot.node('U', 'Xanh nếu không')
dot.node('V', 'Rotate')
dot.node('W', 'Rung và đổi')
dot.node('X', 'Quay lại trạng thái bình thường')
dot.node('Y', 'Thay đổi Material')
dot.node('Z', 'Press Fire để thả block xuống và trở lại trạng thái ban đầu')
dot.node('AA', 'Quản lý Mesh')
dot.node('AB', 'Chế độ Reconstruct?')
dot.node('AC', 'Đưa lại vào pool')
dot.node('AD', 'Xử lý Mesh')
dot.node('AE', 'End')

# Thêm các cạnh (edges)
dot.edges(['AB', 'BC', 'BD'])
dot.edge('B', 'C', 'Có block trong pool')
dot.edge('B', 'D', 'Không có block trong pool')
dot.edge('C', 'E', 'Spawn block từ pool')
dot.edge('D', 'F', 'Instantiate block mới')
dot.edge('E', 'G', 'Block được spawn')
dot.edge('F', 'H', 'Block mới được tạo')
dot.edge('G', 'I')
dot.edge('H', 'I')
dot.edge('I', 'J', 'Quản lý Cube trong Reconstruct Mode')
dot.edge('J', 'K', 'Khi có block')
dot.edge('K', 'L', 'Có')
dot.edge('K', 'M', 'Không')
dot.edge('L', 'N', 'Đưa lại vào pool')
dot.edge('M', 'O', 'Chuyển sang chế độ Reconstruct')
dot.edge('O', 'P', 'Change Material')
dot.edge('P', 'Q', 'Xuất hiện và có các tính năng khác')
dot.edge('Q', 'R', 'Move')
dot.edge('R', 'S', 'Va chạm?')
dot.edge('S', 'T', 'Đỏ nếu có')
dot.edge('S', 'U', 'Xanh nếu không')
dot.edge('Q', 'V', 'Rotate')
dot.edge('V', 'W', 'Rung và đổi')
dot.edge('W', 'X', 'Quay lại trạng thái bình thường')
dot.edge('Q', 'Y', 'Thay đổi Material')
dot.edge('Q', 'Z', 'Press Fire để thả block xuống và trở lại trạng thái ban đầu')
dot.edge('Z', 'AA', 'Quản lý Mesh')
dot.edge('AA', 'AB', 'Chế độ Reconstruct?')
dot.edge('AB', 'AC', 'Đưa lại vào pool')
dot.edge('AB', 'AD', 'Xử lý Mesh')
dot.edge('AD', 'AE', 'End')

# Render và lưu biểu đồ
dot.render('block_management_flowchart', format='png', cleanup=True)

# Hiển thị biểu đồ
dot.view()
