import json

timezone_mapping = {
    "ACDT": "AUS Central Daylight Time",
    "ACST": "AUS Central Standard Time",
    "ACT": "Central Standard Time (Mexico)",
    "ADT": "Atlantic Daylight Time",
    "AEDT": "AUS Eastern Daylight Time",
    "AEST": "AUS Eastern Standard Time",
    "AFT": "Afghanistan Standard Time",
    "AKDT": "Alaskan Daylight Time",
    "AKST": "Alaskan Standard Time",
    "ALMT": "Central Asia Standard Time",
    "AMST": "Central Brazilian Standard Time",
    "AMT": "Central Brazilian Standard Time",
    "ANAT": "Russia TZ 11 Standard Time",
    "AQTT": "West Asia Standard Time",
    "ART": "Argentina Standard Time",
    "AST": "Atlantic Standard Time",
    "AWDT": "W. Australia Daylight Time",
    "AWST": "W. Australia Standard Time",
    "AZOST": "Azores Standard Time",
    "AZT": "Azerbaijan Standard Time",
    "BDT": "Bangladesh Standard Time",
    "BIOT": "Indian Standard Time",
    "BIT": "Central Pacific Standard Time",
    "BOT": "SA Western Standard Time",
    "BRST": "E. South America Daylight Time",
    "BRT": "E. South America Standard Time",
    "BST": "GMT Standard Time",
    "BTT": "Bangladesh Standard Time",
    "CAT": "South Africa Standard Time",
    "CCT": "Myanmar Standard Time",
    "CDT": "Central Daylight Time",
    "CEST": "Central European Summer Time",
    "CET": "Central Europe Standard Time",
    "CHADT": "Chatham Islands Daylight Time",
    "CHAST": "Chatham Islands Standard Time",
    "CKT": "Hawaiian Standard Time",
    "CLST": "Chile Summer Time",
    "CLT": "Chile Standard Time",
    "COT": "SA Pacific Standard Time",
    "CST": "Central Standard Time",
    "CT": "China Standard Time",
    "CVT": "Cape Verde Standard Time",
    "CXT": "Central Asia Standard Time",
    "ChST": "Chamorro Standard Time",
    "DAVT": "West Asia Standard Time",
    "DDUT": "West Asia Standard Time",
    "EAT": "E. Africa Standard Time",
    "ECT": "SA Western Standard Time",
    "EDT": "Eastern Daylight Time",
    "EEST": "E. Europe Daylight Time",
    "EET": "E. Europe Standard Time",
    "EGT": "Azores Standard Time",
    "EST": "Eastern Standard Time",
    "FET": "Kaliningrad Standard Time",
    "FJT": "Fiji Standard Time",
    "FKT": "Falkland Islands Standard Time",
    "FNT": "Montevideo Standard Time",
    "GALT": "Central Standard Time",
    "GAMT": "Central Standard Time",
    "GET": "Georgian Standard Time",
    "GFT": "SA Western Standard Time",
    "GILT": "Hawaiian Standard Time",
    "GMT": "GMT Standard Time",
    "GST": "Gulf Standard Time",
    "GYT": "SA Western Standard Time",
    "HDT": "Hawaiian Standard Time",
    "HKT": "China Standard Time",
    "HOVT": "Yakutsk Standard Time",
    "HST": "Hawaiian Standard Time",
    "ICT": "SE Asia Standard Time",
    "IDT": "Israel Daylight Time",
    "IOT": "Indian Standard Time",
    "IRDT": "Iran Daylight Time",
    "IRKT": "North Asia East Standard Time",
    "IRST": "Iran Standard Time",
    "IST": "India Standard Time",
    "JST": "Tokyo Standard Time",
    "KGT": "Central Asia Standard Time",
    "KOST": "Central Pacific Standard Time",
    "KRAT": "North Asia Standard Time",
    "KST": "Korea Standard Time",
    "LHST": "Lord Howe Standard Time",
    "LINT": "Line Islands Time",
    "MAGT": "Magadan Standard Time",
    "MART": "Central Pacific Standard Time",
    "MAWT": "West Asia Standard Time",
    "MDT": "Mountain Daylight Time",
    "MHT": "Central Pacific Standard Time",
    "MMT": "Myanmar Standard Time",
    "MSK": "Moscow Standard Time",
    "MST": "Mountain Standard Time",
    "MUT": "Mauritius Standard Time",
    "MVT": "Maldives Standard Time",
    "MYT": "Singapore Standard Time",
    "NCT": "Central Pacific Standard Time",
    "NDT": "Newfoundland Daylight Time",
    "NFT": "Central Pacific Standard Time",
    "NOVT": "North Asia Standard Time",
    "NPT": "Nepal Standard Time",
    "NST": "Newfoundland Standard Time",
    "NT": "Newfoundland Standard Time",
    "NUT": "Central Pacific Standard Time",
    "NZDT": "New Zealand Daylight Time",
    "NZST": "New Zealand Standard Time",
    "OMST": "North Asia Standard Time",
    "PDT": "Pacific Daylight Time",
    "PETT": "Russia TZ 11 Standard Time",
    "PHOT": "Phoenix Islands Time",
    "PHT": "Philippine Standard Time",
    "PKT": "Pakistan Standard Time",
    "PONT": "Pohnpei Standard Time",
    "PST": "Pacific Standard Time",
    "RET": "Reunion Standard Time",
    "SAKT": "Russia TZ 10 Standard Time",
    "SAMT": "Russia TZ 3 Standard Time",
    "SAST": "South Africa Standard Time",
    "SBT": "Solomon Islands Time",
    "SCT": "Seychelles Standard Time",
    "SGT": "Singapore Standard Time",
    "SLT": "Sri Lanka Standard Time",
    "SRET": "Russia TZ 11 Standard Time",
    "SRT": "Suriname Standard Time",
    "SST": "Samoa Standard Time",
    "SYOT": "West Asia Standard Time",
    "TAHT": "Hawaiian Standard Time",
    "TFT": "Central Asia Standard Time",
    "TJT": "West Asia Standard Time",
    "TKT": "Central Pacific Standard Time",
    "TLT": "East Timor Standard Time",
    "TMT": "West Asia Standard Time",
    "TVT": "Central Pacific Standard Time",
    "ULAT": "Ulaanbaatar Standard Time",
    "UTC": "UTC",
    "UYST": "Montevideo Daylight Time",
    "UYT": "Montevideo Standard Time",
    "UZT": "West Asia Standard Time",
    "VET": "Venezuela Standard Time",
    "VLAT": "Russia TZ 10 Standard Time",
    "VOLT": "Volgograd Standard Time",
    "VOST": "West Asia Standard Time",
    "VUT": "Central Pacific Standard Time",
    "WAKT": "Central Pacific Standard Time",
    "WAT": "W. Central Africa Standard Time",
    "WET": "Western Europe Standard Time",
    "WGT": "Azores Standard Time",
    "WIB": "SE Asia Standard Time",
    "WIT": "East Indonesia Time",
    "WST": "W. Australia Standard Time",
    "YAKT": "Russia TZ 9 Standard Time",
    "YEKT": "Russia TZ 8 Standard Time"
}
# Đọc tệp JSON
with open('Assets/Resources/timezone_mapping.json', 'r') as file:
    data = json.load(file)

# Chuyển đổi múi giờ viết tắt thành tên đầy đủ
for entry in data:
    if 'Windows' in entry:
        abbreviation = entry['Windows']
        full_timezone_name = timezone_mapping.get(abbreviation, "Unknown")
        entry['Windows'] = full_timezone_name

# Lưu lại kết quả vào tệp JSON mới
with open('Assets/Resources/timezone_mapping.json', 'w') as outfile:
    json.dump(data, outfile, indent=4)

print("Conversion completed and saved to 'full_timezones_for_windows.json'")
